apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoqapp
  labels:
    app: hoqapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoqapp
  template:
    metadata:
      labels:
        app: hoqapp
    spec:
      containers:
      - name: hoqapp
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/hoqapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hoqapp
spec:
  selector:
    app: hoqapp
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hoqapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - <some-domain>
    secretName: auth-tls
  rules:
  - host: <some-domain>
    http:
      paths:
      - path:
        backend:
          serviceName: hoqapp
          servicePort: 8080